#!/usr/bin/env python

import StaticDB as new
import StaticData as old


def main():
    
    testnames = [
        'ATLAS_2014_I1325553',
        'ATLAS_2014_I1268975',
        'ATLAS_2014_I1326641',
        'ATLAS_2013_I1230812_EL',
        'ATLAS_2013_I1217863',
        'ATLAS_2012_I1093738',
        'ATLAS_2012_I1083318',
        'ATLAS_2011_I945498',
        'ATLAS_2011_I921594',
        'ATLAS_2011_S9128077',
        'CMS_2014_I1298810',
        'ATLAS_2013_I1244522',
        'ATLAS_2014_I1306294_EL',
        'CMS_2013_I1256943',
        'CMS_2015_I1310737',
        'CMS_2014_I1303894',
        'ATLAS_2014_I1319490_MU',
        'ATLAS_2014_I1319490_EL',
        'ATLAS_2015_I1394679',
        'ATLAS_2014_I1307243',
        'ATLAS_2013_I1263495',
        'ATLAS_2013_I1217863_Z',
        'ATLAS_2013_I1217863_W_MU',
        'ATLAS_2013_I1217863_W_EL',
        'ATLAS_2012_I1203852',
        'ATLAS_2012_I1199269',
        'CMS_2014_I1266056',
        'ATLAS_2014_I1306294_MU',
        'ATLAS_2013_I1230812_MU',
        'CMS_2013_I1224539_WJET',
        'CMS_2013_I1224539_ZJET',
        'ATLAS_2014_I1279489',
        'ATLAS_2015_I1408516',
        'ATLAS_2016_I1457605',
        'CMS_2013_I1224539',
        'ATLAS_2014_I1279489',
        'ATLAS_2015_I1408516',
    ]

    tags = [ 
        'd%02d-x%02d-y%02d' % (d,x,y) 
        for d in range(1,31)
        for x in range(1,7)
        for y in range(1,7)
    ]


    for h in testnames:
        for tag in tags:
            path = '%s/%s' % (h,tag)

            lf_old = old.LumiFinder(path)
            lf_new = new.LumiFinder(path)

            # map to same INVALID value
            if lf_old[0] == -1:
                lf_old = new.INVALID

            if lf_old != lf_new:
                print path,':',lf_old,':',lf_new


            norm_old = old.isNorm(path)
            norm_new = new.isNorm(path)

            if norm_old != norm_new:
                print path,':',norm_old,':',norm_new




if __name__ == '__main__':
    main()

